services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school_db
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:







# version: '3'
# services:
#   db:
#     build: .
#     container_name: school_api_db
#     restart: always
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d school_db"]
#       interval: 5s
#       timeout: 5s
#       retries: 5
#     environment:
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=school_db
#     ports:
#       - "5454:5432"
#     volumes: 
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: